stages:
  data_processing:
    cmd: python -m src.data.make_dataset OUTPUT_TARGET_FILEPATH=.
    deps:
      - data/raw/test.csv
      - data/raw/train.csv
      - src/data/make_dataset.py
      - src/data/preprocess.py
      - src/config.py
      - src/utils.py
    params:
      - interim_paths
      - data_load
      - preprocess_category
      - processed_paths
    outs:
      - data/processed/target_for_data_for_train.pkl
      - data/interim/data_for_train.pkl
      - data/interim/test.pkl

  feature_generation:
    cmd: python -m src.features.build_features
    deps:
      - src/config.py
      - src/utils.py
      - src/features/functions.py
      - src/features/build_features.py
      - data/interim/data_for_train.pkl
      - data/interim/test.pkl
    params:
      - interim_paths
      - processed_paths
    outs:
      - data/processed/test.pkl
      - data/processed/data_for_train.pkl

  train:
    cmd: python -m src.models.train_model
    deps:
      - src/config.py
      - data/processed/test.pkl
      - data/processed/data_for_train.pkl
    params:
      - base
      - train
      - processed_paths
    outs:
      - models/model.joblib
