base:
  seed: 77

data_load:
  train_csv: 'data/raw/train.csv'
  test_csv: 'data/raw/test.csv'

preprocess_category:
  TARGET_COLS: ['Артериальная гипертензия', 'ОНМК', 'Стенокардия, ИБС, инфаркт миокарда', 'Сердечная недостаточность', 'Прочие заболевания сердца']
  ID_COL: 'ID'
  EDU_COL: 'Образование'
  SEX_COL: 'Пол'
  CAT_COLS: [ 'Пол', 'Семья', 'Этнос', 'Национальность', 'Религия', 'Образование', 'Профессия', 'Статус Курения', 'Частота пасс кур', 'Алкоголь', 'Время засыпания', 'Время пробуждения']
  OHE_COLS: [ 'Пол', 'Вы работаете?', 'Выход на пенсию', 'Прекращение работы по болезни', 'Сахарный диабет', 'Гепатит', 'Онкология', 'Хроническое заболевание легких', 'Бронжиальная астма', 'Туберкулез легких ', 'ВИЧ/СПИД', 'Регулярный прим лекарственных средств', 'Травмы за год', 'Переломы','Пассивное курение', 'Сон после обеда', 'Спорт, клубы', 'Религия, клубы']
  REAL_COLS: ['Возраст курения', 'Сигарет в день', 'Возраст алког']

interim_paths:
  data_for_train_pkl: 'data/interim/data_for_train.pkl'
  test_pkl: 'data/interim/test.pkl'

processed_paths:
  target_data_train_pkl: 'data/processed/target_for_data_for_train.pkl'
  processed_test_pkl: 'data/processed/test.pkl'
  processed_data_for_train_pkl: 'data/processed/data_for_train.pkl'

train:
  CATEGORIES_COL: ['Пол','Семья', 'Этнос', 'Национальность', 'Религия', 'Профессия', 'Статус Курения', 'Частота пасс кур', 'Алкоголь', 'Сова/Жаворонок/Голубь']
  train_size: 0.8
  iterations: 10
  loss_function: 'MultiLogloss'
  eval_metric: 'MultiLogloss'
  learning_rate: 0.2
  bootstrap_type: 'Bayesian'
  boost_from_average: False
  leaf_estimation_iterations: 1
  leaf_estimation_method: 'Gradient'

  model_path: 'models/model.joblib'
  X_test_path: 'data/processed/X_test_data.pkl'
  Y_test_path: 'data/processed/Y_test_data.pkl'

evaluate:
  score_metric: 'f1'
  score_path: 'reports/metrics.json'
